---
apiVersion: v1
kind: Namespace
metadata:
  name: akaunting

# ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: akaunting
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - akaunting.mhemeryck.com
      secretName: akaunting-mhemeryck-com-tls
  rules:
    - host: akaunting.mhemeryck.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: akaunting
                port:
                  number: 80
# mariadb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: akaunting
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: akaunting
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: akaunting-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-data
      containers:
        - name: mariadb
          image: mariadb:lts
          resources:
            limits:
              memory: 1Gi
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_DATABASE
              value: akaunting
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: akaunting
                  key: mysql_password
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: akaunting
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306

# akaunting
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: akaunting
  namespace: akaunting
data:
  APP_URL: https://akaunting.mhemeryck.com
  LOCALE: en-US
  DB_HOST: mariadb
  DB_PORT: "3306"
  DB_NAME: akaunting
  DB_USERNAME: admin
  DB_PREFIX: asd_
  COMPANY_NAME: "Katrien Fagard"
  COMPANY_EMAIL: "katrienfagard@hotmail.com"
  ADMIN_EMAIL: "martijn.hemeryck@gmail.com"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads
  namespace: akaunting
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akaunting
  namespace: akaunting
spec:
  selector:
    matchLabels:
      app: akaunting
  template:
    metadata:
      labels:
        app: akaunting
    spec:
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads
      containers:
        - name: akaunting
          image: docker.io/akaunting/akaunting:3.0.15-v
          ports:
            - containerPort: 80
          volumeMounts:
            - name: uploads
              mountPath: /var/www/html
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: akaunting
                  key: mysql_password
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: akaunting
                  key: admin_password
          envFrom:
            - configMapRef:
                name: akaunting
        #livenessProbe:
        #  httpGet:
        #    path: /health
        #    port: 3000
        #  initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: akaunting
  namespace: akaunting
spec:
  selector:
    app: akaunting
  ports:
    - port: 80
      targetPort: 80
