---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden
spec:
  selector:
    matchLabels:
      app: bitwarden
  template:
    metadata:
      labels:
        app: bitwarden
    spec:
      volumes:
        - name: vault
          persistentVolumeClaim:
            claimName: vault
      containers:
        - name: bitwarden
          image: vaultwarden/server:1.24.0-alpine
          volumeMounts:
            - name: vault
              mountPath: /data
          env:
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: admin_token
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: database_url
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bitwarden
spec:
  selector:
    app: bitwarden
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
