apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvsite
spec:
  selector:
    matchLabels:
      app: cvsite
  replicas: 2
  template:
    metadata:
      labels:
        app: cvsite
    spec:
      containers:
        - name: cvsite
          image: mhemeryck/cvsite:latest
---
apiVersion: v1
kind: Service
metadata:
  name: cvsite
  labels:
    app: cvsite
spec:
  selector:
    app: cvsite
  ports:
    - name: web
      port: 80
