---
apiVersion: v1
kind: Namespace
metadata:
  name: cvsite
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvsite
  namespace: cvsite
spec:
  selector:
    matchLabels:
      app: cvsite
  replicas: 2
  template:
    metadata:
      labels:
        app: cvsite
    spec:
      containers:
        - name: cvsite
          image: mhemeryck/cvsite:latest
---
apiVersion: v1
kind: Service
metadata:
  name: cvsite
  namespace: cvsite
  labels:
    app: cvsite
spec:
  selector:
    app: cvsite
  ports:
    - name: web
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: cvsite
  annotations:
    kubernetes.io/ingress.className: traefik
    cert-manager.io/cluster-issuer: letsencrypt-staging
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - mhemeryck.xyz
      secretName: cv-mhemeryck-xyz-tls
  rules:
    - host: mhemeryck.xyz
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: cvsite
                port:
                  number: 80
