apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvsite
spec:
  selector:
    matchLabels:
      app: cvsite
  replicas: 2
  template:
    metadata:
      labels:
        app: cvsite
    spec:
      containers:
        - name: cvsite
          image: mhemeryck/cvsite:latest
        - name: cvsite-prometheus-exporter
          image: nginx/nginx-prometheus-exporter:0.8.0
          env:
            - name: SCRAPE_URI
              value: http://localhost/metrics
            - name: TELEMETRY_PATH
              value: /metrics
            - name: NGINX_RETRIES
              value: "10"
          ports:
            - containerPort: 9113
---
apiVersion: v1
kind: Service
metadata:
  name: cvsite
  labels:
    app: cvsite
spec:
  selector:
    app: cvsite
  ports:
    - name: web
      port: 80
    - name: metrics
      port: 9113
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cvsite-monitor
  labels:
    app: cvsite
    release: prometheus
spec:
  selector:
    matchLabels:
      app: cvsite
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics
      interval: 15s
