apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - cv.mhemeryck.com
        - mhemeryck.com
      secretName: cv-mhemeryck-com-tls
    - hosts:
        - wekan.mhemeryck.com
      secretName: wekan-mhemeryck-com-tls
    - hosts:
        - bitwarden.mhemeryck.com
      secretName: bitwarden-mhemeryck-com-tls
  rules:
    - host: cv.mhemeryck.com
      http: &cv_http
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: cvsite
                port:
                  number: 80
    - host: mhemeryck.com
      http: *cv_http
    - host: wekan.mhemeryck.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: wekan
                port:
                  number: 80
    - host: bitwarden.mhemeryck.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: bitwarden
                port:
                  number: 80
