apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: letsencrypt
spec:
  tls:
    - hosts:
        - cv.mhemeryck.com
      secretName: cv-mhemeryck-com-tls
  rules:
    - host: cv.mhemeryck.com
      http:
        paths:
          - path: /
            backend:
              serviceName: cvsite-service
              servicePort: 80
