[project]
name = "iac"
revision = "1.0"

[profiles.default]
BILLING_ALERT_EMAIL = { description = "Email address receiving Goalkeepr backup budget alerts", required = true }
DIGITALOCEAN_TOKEN  = { description = "DigitalOcean API token", required = true }
HCLOUD_TOKEN        = { description = "Hetzner Cloud API token", required = true }
