[project]
name = "iac"
revision = "1.0"

[profiles.default]
DIGITALOCEAN_TOKEN  = { description = "DigitalOcean API token", required = true }
HCLOUD_TOKEN        = { description = "Hetzner Cloud API token", required = true }
KUBECONFIG          = { description = "HCloud Kubernetes configuration", required = true, as_path = true }
