---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wekan
spec:
  selector:
    matchLabels:
      app: wekan
  template:
    metadata:
      labels:
        app: wekan
    spec:
      containers:
        - name: wekan
          image: wekanteam/wekan:v7.27
          env:
            - name: MONGO_URL
              value: mongodb://mongodb/wekan
            - name: ROOT_URL
              value: https://wekan.mhemeryck.com
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wekan
spec:
  selector:
    app: wekan
  ports:
    - port: 80
      targetPort: 8080
