---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wekan-app
spec:
  selector:
    matchLabels:
      app: wekan
  template:
    metadata:
      labels:
        app: wekan
    spec:
      containers:
        - name: wekan
          image: wekanteam/wekan:v4.17
          env:
            - name: MONGO_URL
              value: mongodb://mongodb-service:27017/wekan
            - name: ROOT_URL
              value: https://kanban.mhemeryck.com
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wekan-service
spec:
  selector:
    app: wekan
  ports:
    - port: 80
      targetPort: 8080
